embeddings {
  tensor_name: "word_embedding_1:0"
  metadata_path: "/Users/davidtan/Code/learning-materials/learn-machine-learning/ml-data-night/rnn-imdb/./tensorflow.logdir/glove_full_50d.words.tsv"
}
